### ISSUE TITLE
Does not start #2 - dashing json LoadError

### ISSUE THREAD

**Issue by psychofisch** [micke2k/dashinga2#1]
Hello again,
I think this is a dashing problem but because it has no more active support I'll post this here.
It is exactly this problem https://github.com/Shopify/dashing/issues/546.
When I try to start dashinga2 with `dashing start` I get the following error:

```
/home/vagrant/.gem/ruby/gems/dashing-1.3.4/lib/dashing/downloader.rb:3:in `require': cannot load such file -- json (LoadError)
    from /home/vagrant/.gem/ruby/gems/dashing-1.3.4/lib/dashing/downloader.rb:3:in `<top (required)>'
    from /home/vagrant/.gem/ruby/gems/dashing-1.3.4/lib/dashing.rb:2:in `require'
    from /home/vagrant/.gem/ruby/gems/dashing-1.3.4/lib/dashing.rb:2:in `<top (required)>'
    from config.ru:1:in `require'
    from config.ru:1:in `block in <main>'
    from /home/vagrant/.gem/ruby/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
    from /home/vagrant/.gem/ruby/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1:in `<main>'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
    from /home/vagrant/.gem/ruby/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
    from /home/vagrant/bin/thin:23:in `load'
    from /home/vagrant/bin/thin:23:in `<main>'
```

but I have installed the json gem

```
gem list | grep json
json (1.7.7)
multi_json (1.11.2)
```

Can you help me with this?

PS: sry that i haven't answered your question to my last issue but there was the weekend and i have my complete testing environment on my office computer

**Comment by micke2k** [comment]
No worries :)

This issue ive fixed several times.

im using json (1.8.3).

Can you go into /usr/share/dashinga2 and run:
"gem uninstall json"
And then bundle install again?

**Comment by psychofisch** [comment]
ok, so i tried that but it is still not working.
I am not sure but it seems that `bundle install` only installs `multi_json`.
Here's my shell output, I hope it helps^^

```
vagrant@icinga2a$ >gem uninstall json
ERROR:  While executing gem ... (Gem::InstallError)
    json is not installed in GEM_HOME, try:
    gem uninstall -i /usr/share/gems json
vagrant@icinga2a$ >sudo gem uninstall -i /usr/share/gems json
Successfully uninstalled json-1.7.7
vagrant@icinga2a$ >bundle install
Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using backports 3.6.6
Using coffee-script-source 1.9.1.1
Using execjs 2.0.2
Using daemons 1.2.3
Using rack 1.5.5
Using thread_safe 0.3.5
Using sass 3.2.19
Using tilt 1.4.1
Using multi_json 1.11.2
Using hike 1.2.3
Using eventmachine 1.0.8
Using thor 0.18.1
Using unf_ext 0.0.7.1
Using mime-types 2.6.2
Using netrc 0.10.3
Using bundler 1.11.2
Using coffee-script 2.2.0
Using rack-protection 1.5.3
Using rack-test 0.6.3
Using tzinfo 1.2.2
Using sprockets 2.10.2
Using thin 1.6.4
Using unf 0.1.4
Using sinatra 1.4.6
Using rufus-scheduler 2.0.24
Using domain_name 0.5.24
Using sinatra-contrib 1.4.6
Using http-cookie 1.0.2
Using dashing 1.3.4
Using rest-client 1.8.0
Bundle complete! 4 Gemfile dependencies, 30 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
vagrant@icinga2a$ >dashing start
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- json (LoadError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require'
    from /home/vagrant/.gem/ruby/gems/dashing-1.3.6/lib/dashing/downloader.rb:3:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /home/vagrant/.gem/ruby/gems/dashing-1.3.6/bin/dashing:7:in `<top (required)>'
    from /home/vagrant/bin/dashing:23:in `load'
    from /home/vagrant/bin/dashing:23:in `<main>'

```

**Comment by micke2k** [comment]
Can you add it you your gemfile?

I saw now that i have it in my gemfile, but not on the github.

Add to Gemfile:
gem 'json'

Run bundle install after

**Comment by psychofisch** [comment]
Hey! It finally worked^^
Thx =)

**Comment by micke2k** [comment]
Np, check it out and see if it can be improved somehow
